from django.urls import path

from . import views 

urlpatterns = [
    path('login/', views.sign_in, name='login'),
    path('register/', views.register, name='register'),
    path('home/', views.home, name='home'),
    path('mft/', views.mft, name='mft'),
    path('aero/', views.aero, name='aero'),
    path('aqua/', views.aqua, name='aqua'),
    path('hydro/', views.hydro, name='hydro'),
    path('mono/', views.mono, name='mono'),
    path('tissue/', views.tissue, name='tissue'),
    path('customer/', views.customer, name='customer'),
    path('postads/', views.postcropads, name='postads'),
    path('myads/', views.myads, name='myads'),
    path('cmarket/', views.cmarket, name='cmarket'),
    path('newhome/', views.home_new, name='new_home'),
    path('postcomplaint/', views.postcomplaint, name='postcomplaint'),
    path('changepassword/', views.changepassword, name='changepassword'),
    path('addtocart/<int:id>', views.addtocart, name='addtocart'),
    path('sendfrequest/<int:id>', views.sendfrequest, name='sendfrequest'),
    path('sendcrequest/<int:id>', views.sendcrequest, name='sendcrequest'),
    path('profile/', views.profile, name='profile'),
    path('cprofile/', views.cprofile, name='cprofile'),
    path('mycrop/', views.mycrop, name='mycrop'),
    path('deletecrop/<int:id>', views.deletemycrop, name='deletecrop'),
    path('deleteads/<int:id>', views.deletemyads, name='deleteads'),
    path('fmarket/', views.fmarket, name='fmarket'),
    path('frequest/', views.frequest, name='frequest'),
    path('fresponse/', views.fresponse, name='fresponse'),
    path('crequest/', views.crequest, name='crequest'),
    path('cresponse/', views.cresponse, name='cresponse'),
    path('cresaccept/<int:id>', views.cresponseaccept, name='cresponseaccept'),
    path('cresreject/<int:id>', views.cresponsereject, name='cresponsereject'),
    path('fresaccept/<int:id>', views.fresponseaccept, name='fresponseaccept'),
    path('fresreject/<int:id>', views.fresponsereject, name='fresponsereject'),
    path('postcrop/', views.postcrop, name='postcrop'),
    path('croppred/', views.croppred, name='croppred'),
    path('fertilizerpred/', views.fertilizerpred, name='fertilizerpred'),
    path('diseasepred/', views.diseasepred, name='diseasepred'),
    path('dpred/', views.dpred, name='dpred'),
    path('predict/', views.predict, name='predict'),
    path('fertpredict/', views.fertpred, name='fertpred'),
    path('weather/', views.weather, name='weather'),
    path('logout/', views.log_out, name='logout'),
    path('', views.index, name='index')
]
